import type { Metadata } from 'next'
import './globals.css'
import Script from 'next/script'
import Link from 'next/link'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html>
   
    <body>
    <ul>
      <li>
        <Link href="/">Home</Link>
      </li>
      <li>
        <Link href="/sample/triangle">triangle</Link>
      </li>
     </ul>
      
        {children}
    </body>
    </html>
  
  )
}
